/* Automagically generated, do not edit! */
static const u_char t01_head1[] = ""
"<!DOCTYPE html>"
"\n"
"<html>"
"\n"
"<head>"
"\n"
"<meta charset=\"utf-8\">"
"\n"
;
static const u_char t02_head2[] = ""
"<title>Index of "
;
static const u_char t03_head3[] = ""
"</title>"
"\n"
"<style>"
"\n"
"body {"
"margin: 10px 20px;"
"padding: 0;"
"}"
"\n"
"h1 {"
"font-family: Tahoma, Verdana, Arial, sans-serif;"
"}"
"\n"
"#list {"
"width: 100%;"
"border-collapse: collapse;"
"font-family: Consolas, \"Liberation Mono\", Courier, monospace;"
"font-size: 14px;"
"line-height: 18px;"
"}"
"\n"
".date, .size {"
"white-space: nowrap;"
"text-overflow: ellipsis;"
"width: 10%;"
"}"
"\n"
".size {"
"text-align: right;"
"}"
"\n"
"td, th {"
"text-align: left;"
"padding: 5px;"
"border-bottom: 1px solid #ddd;"
"}"
"\n"
"tbody>tr:hover {"
"background: #eee;"
"}"
"\n"
"a {"
"text-decoration: none;"
"}"
"\n"
"a:hover, a:active {"
"text-decoration: underline;"
"}"
"\n"
"</style>"
"\n"
"</head>"
"\n"
;
static const u_char t04_body1[] = ""
"<body>"
"\n"
"<h1>Index of "
;
static const u_char t05_body2[] = ""
"</h1>"
"\n"
;
static const u_char t06_list1[] = ""
"<table id=\"list\">"
"\n"
"<thead>"
"<tr>"
"<th><a href=\"?C=N&O=A\">Name</a>&nbsp;<a href=\"?C=N&O=D\">&nbsp;&#8595;&nbsp;</a></th>"
"<th><a href=\"?C=S&O=A\">Size</a>&nbsp;<a href=\"?C=S&O=D\">&nbsp;&#8595;&nbsp;</a></th>"
"<th><a href=\"?C=M&O=A\">Date</a>&nbsp;<a href=\"?C=M&O=D\">&nbsp;&#8595;&nbsp;</a></th>"
"</tr>"
"</thead>"
"\n"
"<tbody>"
"\n"
;
static const u_char t_parentdir_entry[] = ""
"<tr>"
"<td class=\"name\"><a href=\"../?C=N&amp;O=A\">Parent directory/</a></td>"
"<td>-</td>"
"<td>-</td>"
"</tr>"
"\n"
;
static const u_char t07_list2[] = ""
"</tbody>"
"\n"
"</table>"
"\n"
;
static const u_char t08_foot1[] = ""
"</body>"
"\n"
"</html>"
;
#define NFI_TEMPLATE_SIZE (0 \
	+ nfi_sizeof_ssz(t05_body2) \
	+ nfi_sizeof_ssz(t06_list1) \
	+ nfi_sizeof_ssz(t_parentdir_entry) \
	+ nfi_sizeof_ssz(t07_list2) \
	+ nfi_sizeof_ssz(t08_foot1) \
	+ nfi_sizeof_ssz(t01_head1) \
	+ nfi_sizeof_ssz(t02_head2) \
	+ nfi_sizeof_ssz(t03_head3) \
	+ nfi_sizeof_ssz(t04_body1) \
	)
